### ISSUE TITLE
Application eats up a lot of disk space if cipher files are not closed

### ISSUE THREAD

**Issue by vurazov** [usrflo/encfs4j#1]
- When file system is being used very intensively encfs-", ".dat"  are not removed from temporary directory

**Comment by usrflo** [comment]
"When file system is being used very intensively": could you please explain the scenario in detail?

**Comment by usrflo** [comment]
In reference to #2 I guess you just don't close files. That means that there is temporary need to save temporary files until they can be closed. In a max scenario (not usually) the disk space is increased by the size of all files that are related to CipherFileChannel operations.

**Comment by vurazov** [comment]
"I guess you just don't close files" - sorry, but this is very incorrect (educated) assumption
This bug is not fixed in your solution.
"scenario in detail" - I have very large quantity of files which i need encrypted. It is more then enough for filling any free space

**Comment by usrflo** [comment]
Take a look at the source code to get an idea about the process. The encfs-", ".dat" files only reside in the temp directory if you do not close() those files. There is no bug about that. If you think there may be a bug please report test source code so I can comment on that.

"I have very large quantity of files which i need encrypted. It is more then enough for filling any free space"

Assumed you have about 10GB of encrypted files and 5GB of free disk space. You open all files and start reading them, so tmp-files are created with a potential max size of 10GB. You don't close the file handles. Your system will fail when half of the files are read, as 5GB of temp space is available only.

**Comment by usrflo** [comment]
I checked in a bugfix that removes the tmp file on close() in case reading but no modification of the target file happened: https://github.com/usrflo/encfs4j/commit/c6777d02f086c3d1ae3cdcbcf5f3bec1bc9ca506

Depending on your usage scenario this might reduce the amount of tmp files at runtime.
