### ISSUE TITLE
CipherFileChannel temporarily saves unencrypted files in temp directory

### ISSUE THREAD

**Issue by vurazov** [usrflo/encfs4j#2]
encripted file is decrypted in temporary directory

**Comment by usrflo** [comment]
The temporary directory is used to store files at runtime. Temporary files are deleted if you correctly close a FileChannel by CipherFileChannel.close().
In addition to that this.tmpFile.deleteOnExit() should assure the deletion finally takes place when the JVM is stopped in case you don't close the file channels directly.

I propose you recheck closing files in your source code. This should solve the problem you reported in #1 as well.

**Comment by usrflo** [comment]
I could imagine to create a configurable tmp-file destination. This may be
- a user defined tmp directory instead of java.io.tmpdir
- a tmp file on behalf of another filesystem implementation like https://github.com/marschall/memoryfilesystem

Would this solve your issue?

**Comment by vurazov** [comment]
I dont use temp file, File  is being encrypted/decrypted "on fly"

**Comment by usrflo** [comment]
If tmp files shouldn't be used as intermediary files the overhead of reading / writing becomes enormous. In encryption mode a read operation would require a decryption of 1/2 bytes of file size in average. The same for write operations and according encryption.

You may find a better solution taking a look at block level encryption. For file level encryption the use of tmp/cache files seems to be out of question in my view.
